# Generated by Django 2.1 on 2021-09-01 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210901_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 16, 36, 22, 778171)),
        ),
    ]
