# Generated by Django 3.2.7 on 2021-09-01 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210901_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 16, 38, 54, 610661)),
        ),
    ]
